import Link from "next/link";
import { getStudentAnalytics } from "@/lib/analytics-service";
import { requirePageUser } from "@/lib/page-auth";
import { EmptyState, PageShell, StatCard } from "@/components/page-shell";
import { FilterForm } from "@/components/filter-form";
import { Pagination } from "@/components/pagination";
import { cleanSearch, firstSearchValue, parsePage, type SearchParams } from "@/lib/list-query";
import { listStudentGaps } from "@/lib/learning-lists";

const statuses=["OPEN","IN_PROGRESS","RESOLVED","DISMISSED"] as const;
export default async function LearningProfilePage({searchParams}:{searchParams:Promise<SearchParams>}){const user=await requirePageUser(["STUDENT"]);const parameters=await searchParams;const query=cleanSearch(parameters.query);const statusValue=firstSearchValue(parameters.status);const status=statusValue==="ALL"?undefined:statuses.find(value=>value===statusValue)??"OPEN";const hasExplicitFilter=Boolean(query||statusValue);const page=parsePage(parameters.page);const [analytics,gaps]=await Promise.all([getStudentAnalytics(user.id),listStudentGaps(user.id,{page,pageSize:15,query,status})]);return <PageShell title="学习档案" description="依据真实完成对话形成的趋势和漏洞档案，不代表标准化能力测评。"><section className="stat-grid"><StatCard label="完成闭环" value={analytics.completedSessions}/><StatCard label="形成性平均分" value={analytics.averageScore??"暂无"}/><StatCard label="开放漏洞" value={analytics.openGaps}/><StatCard label="累计会话" value={analytics.totalSessions}/></section><h2>知识漏洞</h2><FilterForm resetHref="/profile/learning"><label>搜索<input name="query" defaultValue={query} placeholder="漏洞、证据或修复任务" maxLength={120}/></label><label>状态<select name="status" defaultValue={statusValue??"OPEN"}><option value="ALL">全部状态</option>{statuses.map(value=><option key={value}>{value}</option>)}</select></label></FilterForm>{gaps.items.length?<div className="data-list">{gaps.items.map(gap=><div className="data-row" key={gap.id}><span className="data-row-detail"><strong>{gap.title}</strong><small>{gap.report.session.topic} · 依据：{gap.evidence} · 修复：{gap.repairTask}</small></span><div className="row-actions"><span className="badge">{gap.status} · 优先级 {gap.priority}</span><Link className="button button-small button-secondary" href={`/report/${gap.report.sessionId}`}>查看来源报告</Link></div></div>)}</div>:<EmptyState title={hasExplicitFilter?"没有匹配漏洞":"暂无待修复漏洞"} description={hasExplicitFilter?"调整搜索或状态筛选后重试。":"完成一次完整学习闭环后，知识漏洞会显示在这里。"}/>}<Pagination pathname="/profile/learning" page={gaps.page} totalPages={gaps.totalPages} query={{query,status:statusValue}}/></PageShell>}
