import Link from "next/link";
import { getStudentAnalytics } from "@/lib/analytics-service";
import { requirePageUser } from "@/lib/page-auth";
import { EmptyState, PageShell, StatCard } from "@/components/page-shell";
import { FilterForm } from "@/components/filter-form";
import { Pagination } from "@/components/pagination";
import { cleanSearch, firstSearchValue, parsePage, type SearchParams } from "@/lib/list-query";
import { listStudentGaps } from "@/lib/learning-lists";
import { gapStatusLabels } from "@/lib/display-labels";

const statuses=["OPEN","IN_PROGRESS","RESOLVED","DISMISSED"] as const;
export default async function LearningProfilePage({searchParams}:{searchParams:Promise<SearchParams>}){const user=await requirePageUser(["STUDENT"]);const parameters=await searchParams;const query=cleanSearch(parameters.query);const statusValue=firstSearchValue(parameters.status);const status=statusValue==="ALL"?undefined:statuses.find(value=>value===statusValue)??"OPEN";const hasExplicitFilter=Boolean(query||statusValue);const page=parsePage(parameters.page);const [analytics,gaps]=await Promise.all([getStudentAnalytics(user.id),listStudentGaps(user.id,{page,pageSize:15,query,status})]);return <PageShell title="学习分析" description="能力表现与待巩固要点，依据已完成研习的形成性评估。"><section className="stat-grid"><StatCard label="完成闭环" value={analytics.completedSessions}/><StatCard label="形成性平均分" value={analytics.averageScore??"暂无"}/><StatCard label="待巩固要点" value={analytics.openGaps}/><StatCard label="累计会话" value={analytics.totalSessions}/></section><h2>待巩固要点</h2><FilterForm resetHref="/profile/learning"><label>搜索<input name="query" defaultValue={query} placeholder="要点、证据或巩固任务" maxLength={120}/></label><label>状态<select name="status" defaultValue={statusValue??"OPEN"}><option value="ALL">全部状态</option>{statuses.map((value)=><option key={value} value={value}>{gapStatusLabels[value]}</option>)}</select></label></FilterForm>{gaps.items.length?<div className="data-list">{gaps.items.map(gap=><div className="data-row" key={gap.id}><span className="data-row-detail"><strong>{gap.title}</strong><small>{gap.report.session.topic} · 依据：{gap.evidence} · 巩固任务：{gap.repairTask}</small></span><div className="row-actions"><span className="badge">{gapStatusLabels[gap.status]} · 优先级 {gap.priority}</span><Link className="button button-small button-secondary" href={`/report/${gap.report.sessionId}`}>查看来源报告</Link></div></div>)}</div>:<EmptyState title={hasExplicitFilter?"没有匹配要点":"暂无待巩固要点"} description={hasExplicitFilter?"调整搜索或状态筛选后重试。":"当前筛选范围内暂无待巩固要点。"}/>}<Pagination pathname="/profile/learning" page={gaps.page} totalPages={gaps.totalPages} query={{query,status:statusValue}}/></PageShell>}
