import { expect, test } from "@playwright/test";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";
import { hash } from "argon2";
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL, max: 2, allowExitOnIdle: true }) });
test.afterAll(async () => prisma.$disconnect());
test("teacher HTML exposes review and blocks publication without review evidence", async ({ page }, testInfo) => {
  const password = "Knowledge-review-test-2026!";
  const user = await prisma.user.create({ data: { email: `review-${crypto.randomUUID()}@example.test`, name: "知识审核测试员", role: "ADMIN", passwordHash: await hash(password) } });
  await page.goto("/login");
  await page.getByLabel("邮箱").fill(user.email); await page.getByLabel("密码").fill(password);
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page).toHaveURL(/\/admin/);
  if ((page.viewportSize()?.width ?? 1440) <= 960) await page.getByRole("button", { name: "打开主导航" }).click();
  const navigation = page.getByRole("navigation", { name: "主导航", exact: true });
  await expect(navigation.getByRole("link")).toHaveCount(7);
  await expect(navigation.getByRole("link", { name: "用户管理" })).toBeVisible();
  await expect(navigation.getByRole("link", { name: "系统状态" })).toBeVisible();
  await navigation.getByRole("link", { name: "知识审核" }).click();
  await expect(page.getByRole("heading", { name: "系统性风险知识审核" })).toBeVisible();
  if (await page.getByRole("button", { name: "建立待审核版本" }).count()) await page.getByRole("button", { name: "建立待审核版本" }).click();
  await expect(page.getByLabel("版本操作")).toBeVisible();
  await page.getByLabel("版本操作").selectOption("PUBLISH");
  await page.getByRole("button", { name: "提交审核操作", exact: true }).click();
  await expect(page.getByRole("status").first()).toContainText("已冻结的候选版本");
  await page.getByRole("tab", { name: "版本概览" }).focus();
  await page.keyboard.press("ArrowRight");
  await expect(page.getByRole("tab", { name: "来源确认" })).toBeFocused();
  await expect(page.getByRole("tab", { name: "来源确认" })).toHaveAttribute("aria-selected", "true");
  const source = page.locator("form").filter({ has: page.getByRole("button", { name: "确认来源", exact: true }) });
  await source.getByLabel("来源标题").fill("仅供自动化测试的合成来源");
  await source.getByLabel("作者或机构").fill("E2E fixture");
  await source.getByLabel("年份").fill("2026");
  await source.getByLabel("来源定位").fill("测试数据库中的合成记录，不用于生产审核");
  await source.getByLabel("来源文件 SHA-256").fill("a".repeat(64));
  await source.getByRole("button", { name: "确认来源", exact: true }).click();
  await expect(source.getByRole("status")).toHaveText("已保存");
  const golden = page.locator("form").filter({ has: page.getByRole("button", { name: "确认样例", exact: true }) });
  await page.getByRole("tab", { name: "样例校准" }).click();
  const checkbox = await golden.locator('input[type="checkbox"]').first().boundingBox();
  expect(checkbox?.width).toBeLessThanOrEqual(24);
  expect(checkbox?.height).toBeLessThanOrEqual(24);
  await golden.getByLabel("学生回答样例").fill("这是自动化测试的学生回答，不属于真实教师确认的校准数据。");
  await golden.getByRole("button", { name: "确认样例", exact: true }).click();
  const savedSample = page.locator("details").filter({ hasText: "这是自动化测试的学生回答，不属于真实教师确认的校准数据。" });
  await expect(savedSample).toHaveCount(1);
  await page.getByRole("tab", { name: "审核记录" }).click();
  await savedSample.locator("summary").click();
  await page.getByRole("button", { name: "撤回此样例" }).click();
  await expect(page.getByRole("button", { name: "撤回此样例" })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("teacher-knowledge-review.png"), fullPage: true });
  await page.getByRole("link", { name: "学生判断复核" }).click();
  await expect(page.getByRole("heading", { name: "学生判断复核" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
