import Link from "next/link";
import { notFound } from "next/navigation";
import { getAssignment } from "@/lib/courses-service";
import { requirePageUser } from "@/lib/page-auth";
import { EmptyState, PageShell, StatCard } from "@/components/page-shell";
import { PublishAssignmentButton } from "@/components/teacher-forms";
import { FilterForm } from "@/components/filter-form";
import { Pagination } from "@/components/pagination";
import { cleanSearch, firstSearchValue, parsePage, type SearchParams } from "@/lib/list-query";
import { listAssignmentStudentProgress } from "@/lib/learning-lists";

const progresses = ["NOT_STARTED", "IN_PROGRESS", "COMPLETED"] as const;
export default async function TeacherAssignmentPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<SearchParams>}){const user=await requirePageUser(["TEACHER"]);const {id}=await params;let item;try{item=await getAssignment(user,id)}catch{notFound()}const parameters=await searchParams;const query=cleanSearch(parameters.query);const progressValue=firstSearchValue(parameters.progress);const progress=progresses.find(value=>value===progressValue);const page=parsePage(parameters.page);const data=await listAssignmentStudentProgress(user,{assignmentId:id,classroomId:item.classroom.id,page,pageSize:20,query,progress});const completed=data.items.filter(entry=>entry.progress==="COMPLETED").length;return <PageShell title={item.title} description={`${item.course.title} · ${item.classroom.name}`} actions={<PublishAssignmentButton assignmentId={id} disabled={item.status!=="DRAFT"}/>}><section className="stat-grid"><StatCard label="状态" value={item.status}/><StatCard label="匹配学生" value={data.total}/><StatCard label="本页完成" value={completed}/><StatCard label="截止时间" value={item.dueAt?new Intl.DateTimeFormat("zh-CN").format(item.dueAt):"未设置"}/></section><article className="card"><h2>学习要求</h2><p>{item.instructions}</p></article><h2>学生进度与真实会话</h2><FilterForm resetHref={`/teacher/assignments/${id}`}><label>学生<input name="query" defaultValue={query} placeholder="姓名或邮箱" maxLength={120}/></label><label>进度<select name="progress" defaultValue={progress??""}><option value="">全部进度</option>{progresses.map(value=><option key={value}>{value}</option>)}</select></label></FilterForm>{data.items.length?<div className="data-list">{data.items.map(entry=>{const session=entry.latestSession;return <div className="data-row" key={entry.id}><span className="data-row-detail"><strong>{entry.student.name}</strong><small>{entry.student.email} · 最近更新 {new Intl.DateTimeFormat("zh-CN").format(entry.updatedAt)}</small></span><div className="row-actions"><span className="badge">{entry.progress}</span>{session?.report?<Link className="button button-small button-secondary" href={`/report/${session.id}`}>查看报告 {session.report.overallScore} 分</Link>:session?<Link className="button button-small button-secondary" href={`/session/${session.id}`}>查看会话</Link>:<small>尚未开始</small>}</div></div>})}</div>:<EmptyState title="没有匹配学生" description="调整姓名或进度筛选后重试。"/>}<Pagination pathname={`/teacher/assignments/${id}`} page={data.page} totalPages={data.totalPages} query={{query,progress}}/></PageShell>}
