"use client";

import { FormEvent, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { AsyncFeedback, idleFeedback, type AsyncFeedbackState } from "./async-feedback";
import { ClientApiError, feedbackForError, readApiResponse } from "@/lib/client-api";

interface SignedUploadData { material: { id: string }; upload: { url: string; headers: Record<string, string> } }
interface UploadAttempt { title: string; chapterId?: string; file: File; signed?: SignedUploadData; transferred: boolean }

export function MaterialUploadForm({courseId,chapters}:{courseId:string;chapters:Array<{id:string;title:string}>}) {
  const router=useRouter(); const [pending,setPending]=useState(false); const [feedback,setFeedback]=useState<AsyncFeedbackState>(idleFeedback); const [attempt,setAttempt]=useState<UploadAttempt|null>(null); const formRef=useRef<HTMLFormElement|null>(null);
  async function execute(current: UploadAttempt):Promise<void>{setPending(true);try{if(!current.signed){setFeedback({kind:"loading",message:"正在申请私有上传地址…"});const lower=current.file.name.toLowerCase();const mimeType=current.file.type||(lower.endsWith(".md")?"text/markdown":"text/plain");const response=await fetch("/api/materials/upload-url",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({courseId,chapterId:current.chapterId,title:current.title,fileName:current.file.name,mimeType,byteSize:current.file.size})});current.signed=await readApiResponse<SignedUploadData>(response,"无法申请上传地址。");}if(!current.transferred){setFeedback({kind:"loading",message:"正在传输文件，请勿关闭页面…"});const upload=await fetch(current.signed.upload.url,{method:"PUT",headers:current.signed.upload.headers,body:current.file});if(!upload.ok){if(upload.status===403)current.signed=undefined;throw new ClientApiError("文件传输失败，请重试。",true)}current.transferred=true;}setFeedback({kind:"loading",message:"正在校验文件并加入处理队列…"});const complete=await fetch("/api/materials/complete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({materialId:current.signed.material.id})});await readApiResponse(complete,"上传确认失败，请重试。");setFeedback({kind:"success",message:"文件已安全上传并进入处理队列。"});setAttempt(null);formRef.current?.reset();router.refresh()}catch(error){setFeedback(feedbackForError(error,"材料上传失败，请重试。"))}finally{setPending(false)}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const file=form.get("file");if(!(file instanceof File)||file.size===0){setFeedback({kind:"error",message:"请选择文件。",retryable:false});return}const current={title:String(form.get("title")),chapterId:String(form.get("chapterId"))||undefined,file,transferred:false};setAttempt(current);await execute(current)}
  return <form ref={formRef} className="stack-form card" onSubmit={submit} aria-busy={pending}><h2>上传课程材料</h2><label>材料标题<input name="title" required minLength={2}/></label><label>章节（可选）<select name="chapterId"><option value="">整门课程</option>{chapters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>文件（PDF、DOCX、TXT、MD，最大 20MB）<input name="file" type="file" required accept=".pdf,.docx,.txt,.md"/></label><AsyncFeedback state={feedback} onRetry={attempt&&!pending?()=>void execute(attempt):undefined}/><button className="button" disabled={pending}>{pending?"上传处理中…":"上传材料"}</button></form>
}
